#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Set fzf options
export FZF_DEFAULT_COMMAND="ag --all-text --hidden --ignore .git -g ''"
export FZF_DEFAULT_OPTS=""

# Set ERL flags
export ERL_AFLAGS="-kernel shell_history enabled"

# Set JVM options
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dsun.java2d.xrender=true"
