#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Set infrastructure dirs
[[ ! -d "${ZDOTDIR:-$HOME}/.local/infrastructure" ]] && mkdir -p "${ZDOTDIR:-$HOME}/.local/infrastructure"

if (( $#commands[(i)vagrant] )); then
  [[ ! -d "${ZDOTDIR:-$HOME}/.local/infrastructure/vagrant" ]] && mkdir -p "${ZDOTDIR:-$HOME}/.local/infrastructure/vagrant"
  export VAGRANT_HOME="${ZDOTDIR:-$HOME}/.local/infrastructure/vagrant"
fi
